{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyM4+o+2rlhVJvgs5SXEvZq2"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"Jq4E9zftlMau","executionInfo":{"status":"ok","timestamp":1737022602097,"user_tz":-330,"elapsed":1416,"user":{"displayName":"Mantesh Eksambe","userId":"16858462400024629873"}},"outputId":"89840ac4-cbdd-4f47-ea3a-3f41d62174d8"},"outputs":[{"output_type":"stream","name":"stdout","text":["Cloning into 'handwritten-digit-recognition'...\n","remote: Enumerating objects: 161, done.\u001b[K\n","remote: Counting objects: 100% (37/37), done.\u001b[K\n","remote: Compressing objects: 100% (33/33), done.\u001b[K\n","remote: Total 161 (delta 13), reused 14 (delta 3), pack-reused 124 (from 1)\u001b[K\n","Receiving objects: 100% (161/161), 1.76 MiB | 8.66 MiB/s, done.\n","Resolving deltas: 100% (53/53), done.\n"]}],"source":["!git clone https://github.com/aakashjhawar/handwritten-digit-recognition.git"]},{"cell_type":"code","source":["cd /content/handwritten-digit-recognition"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"v0hlCr7hoRlv","executionInfo":{"status":"ok","timestamp":1737022849866,"user_tz":-330,"elapsed":387,"user":{"displayName":"Mantesh Eksambe","userId":"16858462400024629873"}},"outputId":"1cf33e18-2152-4bb7-cb3d-dc6e36df5404"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["/content/handwritten-digit-recognition\n"]}]},{"cell_type":"code","source":["!python -m pip install -r requirements.txt"],"metadata":{"id":"EMw4EppwoX4z"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["!python load_model.py /content/handwritten-digit-recognition/assets/images/1a.jpg"],"metadata":{"id":"W3zpQ4r7pEF-","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1737025085959,"user_tz":-330,"elapsed":5997,"user":{"displayName":"Mantesh Eksambe","userId":"16858462400024629873"}},"outputId":"3b1902a9-6d37-4d60-e675-9bd7b7748395"},"execution_count":22,"outputs":[{"output_type":"stream","name":"stdout","text":["2025-01-16 10:58:00.349308: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n","2025-01-16 10:58:00.382478: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n","2025-01-16 10:58:00.392383: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n","2025-01-16 10:58:02.075986: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n","2025-01-16 10:58:04,087 - DEBUG - Starting main function with image_path: /content/handwritten-digit-recognition/assets/images/1a.jpg\n","2025-01-16 10:58:04,088 - DEBUG - Attempting to load the model from: /content/handwritten-digit-recognition/tf-cnn-model.h5\n","2025-01-16 10:58:04,091 - DEBUG - Creating converter from 3 to 5\n","/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n","  super().__init__(activity_regularizer=activity_regularizer, **kwargs)\n","/usr/local/lib/python3.11/dist-packages/keras/src/optimizers/base_optimizer.py:33: UserWarning: Argument `decay` is no longer supported and will be ignored.\n","  warnings.warn(\n","2025-01-16 10:58:04,262 - ERROR - Failed to load model: Invalid value for argument `reduction`. Expected one of {None, 'sum_over_batch_size', 'none', 'sum'}. Received: reduction=auto\n","2025-01-16 10:58:04,262 - ERROR - [ERROR]: Unexpected error: Invalid value for argument `reduction`. Expected one of {None, 'sum_over_batch_size', 'none', 'sum'}. Received: reduction=auto\n","[ERROR]: Unexpected error occurred. Check logs for details.\n"]}]},{"cell_type":"code","source":["!python tf_cnn.py"],"metadata":{"id":"HWo7wF8Hs2wg"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["!python --version"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"AlwEnSkSv-k-","executionInfo":{"status":"ok","timestamp":1737024910207,"user_tz":-330,"elapsed":533,"user":{"displayName":"Mantesh Eksambe","userId":"16858462400024629873"}},"outputId":"89a35a6a-0102-4aa7-e395-3be97b57f508"},"execution_count":19,"outputs":[{"output_type":"stream","name":"stdout","text":["Python 3.11.11\n"]}]}]}
